on: 
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag'     
        required: true

name: Manual Release

jobs:
  build:
    name: Build and release binaries
    runs-on: ${{ matrix.job.os }}
    strategy:
      matrix:
        job:
          - { os: ubuntu-24.04, target: aarch64-unknown-linux-gnu, use-cross: true }
          - { os: ubuntu-24.04, target: x86_64-unknown-linux-gnu }
          - { os: ubuntu-22.04, target: aarch64-unknown-linux-gnu, use-cross: true }
          - { os: ubuntu-22.04, target: x86_64-unknown-linux-gnu }
          - { os: macos-latest , target: x86_64-apple-darwin }
          - { os: macos-latest , target: aarch64-apple-darwin }
          - { os: windows-latest, target: x86_64-pc-windows-msvc }
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.job.target }}
          override: true
          profile: minimal
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.job.use-cross }}
          command: build
          args: --release --target=${{ matrix.job.target }}
      - name: Archive build result
        if: startsWith(matrix.job.os, 'ubuntu') || startsWith(matrix.job.os, 'macos')
        run: tar -C target/${{ matrix.job.target }}/release -czvf target/${{ matrix.job.os }}-${{ matrix.job.target }}.tar.gz vssh
      - name: Zip build result
        if: startsWith(matrix.job.os, 'windows')
        run: 7z a target/${{ matrix.job.os }}-${{ matrix.job.target }}.zip ./target/${{ matrix.job.target }}/release/vssh.exe
      - name: Upload build result as artifact
        if: startsWith(matrix.job.os, 'ubuntu') || startsWith(matrix.job.os, 'macos')
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact-${{ matrix.job.os }}-${{ matrix.job.target }}
          path: target/${{ matrix.job.os}}-${{ matrix.job.target }}.tar.gz
      - name: Upload build result as artifact
        if: startsWith(matrix.job.os, 'windows')
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact-${{ matrix.job.os }}-${{ matrix.job.target }}
          path: target/${{ matrix.job.os}}-${{ matrix.job.target }}.zip
  release:
    name: Create release
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Create release directory
        run: mkdir release
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: build-artifact-*
          path: release
          merge-multiple: true
      - name: Generate checksum
        uses: jmgilman/actions-generate-checksum@v1
        with:
          patterns: |
            release/*.zip
            release/*.tar.gz
      - name: Create release with artifact
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          files: |
            release/*
            checksum.txt